name: compile

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  compile:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        # Probably need different architectures too, e.g. M1 Macs?

    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
        if: runner.os != 'Windows'

      - uses: jiro4989/setup-nim-action@v1

      # once we have release builds we should swap these two lines
      # so that our tests get better errors
      - run: nimble build -d:danger -d:release --opt:speed -Y
      - run: |
          mv native_main.py native_main-x86.py
          nimble build -d:danger -d:release --opt:speed -Y --cpu:arm64
          mv native_main.py native_main-arm64.py
          lipo -create -output native_main.py native_main-x86.py native_main-arm64.py
        if: runner.os == 'macOS'
      # - run: nimble build -d:debug

      # - run: nimble test -Y
      
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: native_main-${{ runner.os }}
          path: native_main.py
